### PR TITLE
Make host alive alarm only send one notification per target

### PR DESCRIPTION
**Pull request by dlfryar-zz**
Notification engine changes to follow which include dimensions
in the body of the notification

An array of dimension maps for a singular alarm show which
hosts triggered an alarm for a given target_host

{
  "dimensions": {
    "test_type": "ping",
    "hostname": "mini-mon",
    "observer_host": "mini-mon",
    "service": "monitoring",
    "target_host": "192.168.10.6"
  },
  "id": null,
  "name": "host_alive_status"
},
{
  "dimensions": {
    "test_type": "ping",
    "hostname": "devstack",
    "observer_host": "devstack",
    "target_host": "192.168.10.6"
},

### CODE REVIEW

**Comment by tkuhlman** [comment]
This a duplicate of the change already made a couple of weeks ago? https://github.com/hpcloud-mon/ansible-monasca-default-alarms/pull/14

**Comment by dlfryar-zz** [comment]
Somewhat, but hostname is removed making the match_by only on target_host.

**Comment by dlfryar-zz** [comment]
Internal JIRA 1902 for reference.

**Comment by tkuhlman** [comment]
It is a mistake to remove hostname. Without hostname two boxes doing a check against a 3rd will only show up as one alarm. Better to show up as two alarms that way you can have the two check boxes in different network segments and better understand how it is that the target box can't be reached.

**Comment by dlfryar-zz** [comment]
That's why I'm making the notification engine change adding the dimensions for the alarm.  As it stands today if you have n-number of nodes monitoring nodeA and nodeA goes down, you get n-alarms and n-notifications.  Then when nodeA comes back up you get the same n-notifications that it came back up.

With this change if nodeA goes down, you get one alarm that says nodeA is down and the dimensions describe the observers.

Is there an issue you see doing it that way.  In the current example one notification is much more helpful than n-number of them as it is much more overhead.

**Comment by tkuhlman** [comment]
I went back and reread the bit at the top about notification engine changes, I guess I don't understand how this is going to work with those changes in place. Perhaps when you have those changes ready it will make more sense to me.

**Comment by tkuhlman** [comment]
Joe explained to me what is happening. I didn't remember that thresh pushes all the dimensions to the notification engine.

FYI, You still have to rebase this change.

**Comment by dlfryar-zz** [comment]
You want to just update your 2015.1.2 tag by removing hostname and close this one to make it easier and more contiguous?

This change is off master and the conflict is from the 2015.1.2 tag.

**Comment by tkuhlman** [comment]
I'm not sure what you are talking about regarding the tag? Github says this branch can not be merged. That is because it is based off an old version of the tree. This has nothing to do with a tag.

**Comment by dlfryar-zz** [comment]
My fork needed a rebase off hpcloud-mon/ansible-monasca-default-alarms/master

**Pull request closed without merging**
